# Site settings
title: Your awesome title
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: I love Emacs and Clojure(Script).

# Social icons
facebook: vmfhrmfoaj
linkedin: vmfhrmfoaj
github: vmfhrmfoaj
gplus: JinseopKim
twitter: _JinseopKim

footer: © Taken theme

# Build settings
markdown: kramdown
